# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers

class TestUnionFoo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTestUnionFoo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TestUnionFoo()
        x.Init(buf, n + offset)
        return x

    # TestUnionFoo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TestUnionFoo
    def FooValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TestUnionFooStart(builder): builder.StartObject(1)
def TestUnionFooAddFooValue(builder, fooValue): builder.PrependInt8Slot(0, fooValue, 0)
def TestUnionFooEnd(builder): return builder.EndObject()
