# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers

class TestStructStruct(object):
    __slots__ = ['_tab']

    # TestStructStruct
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TestStructStruct
    def A(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TestStructStruct
    def B(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # TestStructStruct
    def E(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateTestStructStruct(builder, a, b, e):
    builder.Prep(4, 12)
    builder.Pad(3)
    builder.PrependInt8(e)
    builder.PrependFloat32(b)
    builder.Pad(3)
    builder.PrependUint8(a)
    return builder.Offset()
