# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers

class TestEnum(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTestEnum(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TestEnum()
        x.Init(buf, n + offset)
        return x

    # TestEnum
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TestEnum
    def TestFlag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TestEnum
    def TestEnum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 5

def TestEnumStart(builder): builder.StartObject(2)
def TestEnumAddTestFlag(builder, testFlag): builder.PrependUint16Slot(0, testFlag, 0)
def TestEnumAddTestEnum(builder, testEnum): builder.PrependInt8Slot(1, testEnum, 5)
def TestEnumEnd(builder): return builder.EndObject()
