# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers

class TestUnion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTestUnion(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TestUnion()
        x.Init(buf, n + offset)
        return x

    # TestUnion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TestUnion
    def FoobarType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TestUnion
    def Foobar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def TestUnionStart(builder): builder.StartObject(2)
def TestUnionAddFoobarType(builder, foobarType): builder.PrependUint8Slot(0, foobarType, 0)
def TestUnionAddFoobar(builder, foobar): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(foobar), 0)
def TestUnionEnd(builder): return builder.EndObject()
