# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers

class TestUnionBar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTestUnionBar(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TestUnionBar()
        x.Init(buf, n + offset)
        return x

    # TestUnionBar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TestUnionBar
    def BarValueA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TestUnionBar
    def BarValueB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def TestUnionBarStart(builder): builder.StartObject(2)
def TestUnionBarAddBarValueA(builder, barValueA): builder.PrependUint64Slot(0, barValueA, 0)
def TestUnionBarAddBarValueB(builder, barValueB): builder.PrependUint64Slot(1, barValueB, 0)
def TestUnionBarEnd(builder): return builder.EndObject()
